[package]
name = "project5"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
select = "0.5.0"
url = "2.2.2"
rustls = "0.20.0"
webpki = "0.22.0"
webpki-roots = "0.22.1"